use super::{
    bytecode::{Bytecode, Opcode},
    encoder::Word,
    instruction::{CmpType, ValueType},
};

fn get_type_print(value: ValueType) -> (char, &'static str) {
    match value {
        ValueType::Double => ('d', "double"),
        ValueType::Float => ('f', "float"),
        ValueType::Int32 => ('i', "int32"),
        ValueType::Int64 => ('l', "int64"),
        ValueType::Bool => ('b', "bool"),
        ValueType::Var => ('v', "var"),
        ValueType::String => ('s', "string"),
        ValueType::Int16 => ('e', "int16"),
    }
}

pub fn print_disassembly(bytecode: &Bytecode) {
    log::debug!("Generated bytecode:");

    let chunks: Vec<&[u8]> = bytecode.data.chunks_exact(4).collect();

    for (i, &chunk) in chunks.iter().enumerate() {
        let instr = u32::from_le_bytes(chunk.try_into().unwrap());
        let word = Word::from_u32(instr);

        let opcode = word.opcode;
        let instr_type1 = word.instr_type1;
        let instr_type2 = word.instr_type2;
        let instr_instance_type = word.instr_instance_type;
        let extra_data: Vec<u32> = chunks[i + 1..]
            .iter()
            .map(|&chunk| u32::from_le_bytes(chunk.try_into().unwrap()))
            .collect();

        if let Ok(opcode) = Opcode::try_from(opcode as u32) {
            let pc = i * 4;
            log::debug!(
                "{offset:04X}: [0x{instr:08X}] {rest_of_log}",
                offset = pc,
                instr = instr,
                rest_of_log = match opcode {
                    Opcode::Add
                    | Opcode::Sub
                    | Opcode::Mul
                    | Opcode::Div
                    | Opcode::Rem
                    | Opcode::Mod
                    | Opcode::And
                    | Opcode::Or
                    | Opcode::Xor
                    | Opcode::Shl
                    | Opcode::Shr => {
                        format!(
                            "{opcode:?}.{type2_char}.{type1_char} (pops: [a, b] -> pushes: [result])",
                            type1_char =
                                get_type_print(ValueType::try_from(instr_type1 as u8).unwrap()).0,
                            type2_char =
                                get_type_print(ValueType::try_from(instr_type2 as u8).unwrap()).0
                        )
                    }

                    Opcode::Neg | Opcode::Not => {
                        format!(
                            "{opcode:?}.{type2_char} (pops: [a] -> pushes: [result])",
                            type2_char =
                                get_type_print(ValueType::try_from(instr_type2 as u8).unwrap()).0
                        )
                    }

                    Opcode::Conv => {
                        let from_type = ValueType::try_from(instr_type2 as u8).unwrap();
                        let to_type = ValueType::try_from(instr_type1 as u8).unwrap();
                        format!(
                            "{opcode:?}.{from_char}.{to_char} (pops: [{from_str}] -> pushes: [{to_str}])",
                            from_char = get_type_print(from_type).0,
                            to_char = get_type_print(to_type).0,
                            from_str = get_type_print(from_type).1,
                            to_str = get_type_print(to_type).1
                        )
                    }

                    Opcode::Cmp => {
                        let type1_print =
                            get_type_print(ValueType::try_from(instr_type1 as u8).unwrap());
                        let type2_print =
                            get_type_print(ValueType::try_from(instr_type2 as u8).unwrap());
                        let cmp_type =
                            CmpType::try_from(instr_instance_type).unwrap_or(CmpType::None);
                        format!(
                            "{opcode:?}.{type2_char}.{type1_char} {cmp_type:?} (pops: [{type2_str}, {type1_str}] -> pushes: [bool])",
                            type1_char = type1_print.0,
                            type2_char = type2_print.0,
                            cmp_type = cmp_type,
                            type1_str = type1_print.1,
                            type2_str = type2_print.1,
                        )
                    }

                    Opcode::Push => {
                        let value_type = ValueType::try_from(instr_type2 as u8).unwrap();
                        let type_print = get_type_print(value_type);
                        if value_type == ValueType::Int16 {
                            format!(
                                "{opcode:?}.{type2_char} {num} (pushes: [{type2_str}])",
                                type2_char = type_print.0,
                                type2_str = type_print.1,
                                num = instr_instance_type
                            )
                        } else {
                            format!(
                                "{opcode:?}.{type2_char} 0x{extra_data:8X} (pushes: [{type2_str}])",
                                type2_char = type_print.0,
                                type2_str = type_print.1,
                                extra_data = extra_data[0]
                            )
                        }
                    }

                    Opcode::PushI => {
                        format!(
                            "{opcode:?}.{type2_char} {num} (pushes: [{type2_str}])",
                            type2_char =
                                get_type_print(ValueType::try_from(instr_type2 as u8).unwrap()).0,
                            type2_str =
                                get_type_print(ValueType::try_from(instr_type2 as u8).unwrap()).1,
                            num = instr_instance_type
                        )
                    }

                    Opcode::Pop => {
                        format!(
                            "{opcode:?}.{type2_char}.{type1_char} 0x{extra_data:8X} (pops: [{type2_str}])",
                            type2_char =
                                get_type_print(ValueType::try_from(instr_type2 as u8).unwrap()).0,
                            type1_char =
                                get_type_print(ValueType::try_from(instr_type1 as u8).unwrap()).0,
                            type2_str =
                                get_type_print(ValueType::try_from(instr_type2 as u8).unwrap()).1,
                            extra_data = extra_data[0]
                        )
                    }

                    Opcode::Branch | Opcode::BranchTrue | Opcode::BranchFalse => {
                        let rel_words = ((instr << 9) as i32) >> 9;
                        let rel_bytes = rel_words * 4;
                        let target = (pc as i32 + rel_words * 4) as u32;
                        format!(
                            "{opcode:?} L_{target:04X} (offset: {rel_bytes:+})",
                            target = target,
                            rel_bytes = rel_bytes
                        )
                    }

                    Opcode::Call => {
                        let function_ref = extra_data[0];
                        let args_len = instr_instance_type;
                        format!(
                            "{opcode:?}.{type2_char} (function_ref: 0x{function_ref:08X}, args_len: {args_len})",
                            type2_char =
                                get_type_print(ValueType::try_from(instr_type2 as u8).unwrap()).0,
                            function_ref = function_ref,
                            args_len = args_len
                        )
                    }

                    Opcode::Break => {
                        let sub = i16::from_le_bytes(instr_instance_type.to_le_bytes());
                        let name = match sub {
                            -1 => "chkindex",
                            -2 => "pushaf",
                            -3 => "popaf",
                            -4 => "pushac",
                            -5 => "setowner",
                            -6 => "isstaticok",
                            -7 => "setstatic",
                            -8 => "savearef",
                            -9 => "restorearef",
                            -10 => "isnullish",
                            -11 => "pushref",
                            _ => "unknown",
                        };

                        format!("Break.{name}.e ({sub})")
                    }

                    Opcode::Ret => {
                        let return_type = ValueType::try_from(instr_type1 as u8).unwrap();
                        format!(
                            "{opcode:?}.{type_char} (pops: [value] -> return)",
                            type_char = get_type_print(return_type).0
                        )
                    }

                    Opcode::Exit => "Exit".to_string(),

                    Opcode::PopZ => {
                        format!("PopZ (pops: [value])")
                    }
                }
            );
        }
    }
}
