use crate::{
    bytecode::{Bytecode, Opcode},
    instruction::ValueType,
};

fn get_type_print(value: ValueType) -> (char, &'static str) {
    match value {
        ValueType::Double => ('d', "double"),
        ValueType::Float => ('f', "float"),
        ValueType::Int32 => ('i', "int32"),
        ValueType::Int64 => ('l', "int64"),
        ValueType::Bool => ('b', "bool"),
        ValueType::Var => ('v', "var"),
        ValueType::String => ('s', "string"),
        ValueType::Int16 => ('e', "int16"),
    }
}

pub fn print_disassembly(bytecode: &Bytecode) {
    println!("Generated bytecode:");

    let chunks: Vec<&[u8]> = bytecode.data.chunks_exact(4).collect();

    for (i, &chunk) in chunks.iter().enumerate() {
        let instr = u32::from_le_bytes(chunk.try_into().unwrap());

        let opcode = (instr >> 24) & 0xFF;
        let instr_type1 = (instr >> 20) & 0xF;
        let instr_type2 = (instr >> 16) & 0xF;
        let instr_instance_type = instr & 0xFFFF;
        let extra_data: Vec<u32> = chunks[i + 1..]
            .iter()
            .map(|&chunk| u32::from_le_bytes(chunk.try_into().unwrap()))
            .collect();

        if let Ok(opcode) = Opcode::try_from(opcode) {
            let offset = i * 4;
            print!("{offset:04X}: [0x{instr:08X}] ");
            match opcode {
                Opcode::Add
                | Opcode::Sub
                | Opcode::Mul
                | Opcode::Div
                | Opcode::Rem
                | Opcode::Mod
                | Opcode::And
                | Opcode::Or
                | Opcode::Xor
                | Opcode::Shl
                | Opcode::Shr => {
                    println!(
                        "{opcode:?}.{type1_char}.{type2_char} (pops: [a, b] -> pushes: [result])",
                        type1_char =
                            get_type_print(ValueType::try_from(instr_type1 as u8).unwrap()).0,
                        type2_char =
                            get_type_print(ValueType::try_from(instr_type2 as u8).unwrap()).0
                    );
                }

                Opcode::Neg | Opcode::Not => {
                    println!(
                        "{opcode:?}.{type1_char} (pops: [a] -> pushes: [result])",
                        type1_char =
                            get_type_print(ValueType::try_from(instr_type1 as u8).unwrap()).0
                    );
                }

                Opcode::Push => {
                    let type_print =
                        get_type_print(ValueType::try_from(instr_type1 as u8).unwrap());
                    println!(
                        "{opcode:?}.{type1_char} (pops: [] -> pushes: [{type1_str}])",
                        type1_char = type_print.0,
                        type1_str = type_print.1
                    );
                }

                Opcode::PushI => {
                    println!(
                        "{opcode:?}.{type1_char} (pops: [] -> pushes: [int16])",
                        type1_char =
                            get_type_print(ValueType::try_from(instr_type1 as u8).unwrap()).0
                    )
                }

                Opcode::Pop => {
                    println!(
                        "{opcode:?}.{type1_char}.{type2_char} 0x{extra_data:8X} (pops: [var] -> pushes: [])",
                        type1_char =
                            get_type_print(ValueType::try_from(instr_type1 as u8).unwrap()).0,
                        type2_char =
                            get_type_print(ValueType::try_from(instr_type2 as u8).unwrap()).0,
                        extra_data = extra_data[0]
                    );
                }

                _ => println!("{opcode:?} (type1: 0x{instr_type1:X}, type2: 0x{instr_type2:X})"),
            }
        }
    }
}

pub fn _print_disassembly(bytecode: &Bytecode) {
    println!("Generated bytecode:");
    let mut current: Option<String> = None;

    for chunk in bytecode.data.chunks_exact(4) {
        let instr = u32::from_le_bytes(chunk.try_into().unwrap());
        let opcode = (instr >> 24) & 0xFF;
        let instr_type1 = (instr >> 20) & 0xF;
        let instr_type2 = (instr >> 16) & 0xF;
        let instr_instance_type = instr & 0xFFFF;

        if let Ok(op) = Opcode::try_from(opcode) {
            if let Some(line) = current.take() {
                println!("{line})");
            }

            current = Some(format!(
                "0x{instr:08X}: {op:?} (type1: 0x{instr_type1:X}, type2: 0x{instr_type2:X}"
            ));
        } else if let Some(line) = current.as_mut() {
            line.push_str(&format!(", instr: 0x{instr:08X}"));
        }
    }

    if let Some(line) = current {
        println!("{line})");
    }
}
