use crate::{
    bytecode::{Bytecode, Opcode},
    instruction::ValueType,
};

fn get_type_print(value: ValueType) -> (char, &'static str) {
    match value {
        ValueType::Double => ('d', "double"),
        ValueType::Float => ('f', "float"),
        ValueType::Int32 => ('i', "int32"),
        ValueType::Int64 => ('l', "int64"),
        ValueType::Bool => ('b', "bool"),
        ValueType::Var => ('v', "var"),
        ValueType::String => ('s', "string"),
        ValueType::Int16 => ('e', "int16"),
    }
}

pub fn print_disassembly(bytecode: &Bytecode) {
    log::debug!("Generated bytecode:");

    let chunks: Vec<&[u8]> = bytecode.data.chunks_exact(4).collect();

    for (i, &chunk) in chunks.iter().enumerate() {
        let instr = u32::from_le_bytes(chunk.try_into().unwrap());

        let opcode = (instr >> 24) & 0xFF;
        let instr_type1 = (instr >> 16) & 0xF;
        let instr_type2 = (instr >> 20) & 0xF;
        let instr_instance_type = instr & 0xFFFF;
        let extra_data: Vec<u32> = chunks[i + 1..]
            .iter()
            .map(|&chunk| u32::from_le_bytes(chunk.try_into().unwrap()))
            .collect();

        if let Ok(opcode) = Opcode::try_from(opcode) {
            let offset = i * 4;
            log::debug!(
                "{offset:04X}: [0x{instr:08X}] {rest_of_log}",
                offset = offset,
                instr = instr,
                rest_of_log = match opcode {
                    Opcode::Add
                    | Opcode::Sub
                    | Opcode::Mul
                    | Opcode::Div
                    | Opcode::Rem
                    | Opcode::Mod
                    | Opcode::And
                    | Opcode::Or
                    | Opcode::Xor
                    | Opcode::Shl
                    | Opcode::Shr => {
                        format!(
                            "{opcode:?}.{type1_char}.{type2_char} (pops: [a, b] -> pushes: [result])",
                            type1_char =
                                get_type_print(ValueType::try_from(instr_type1 as u8).unwrap()).0,
                            type2_char =
                                get_type_print(ValueType::try_from(instr_type2 as u8).unwrap()).0
                        )
                    }

                    Opcode::Neg | Opcode::Not => {
                        format!(
                            "{opcode:?}.{type1_char} (pops: [a] -> pushes: [result])",
                            type1_char =
                                get_type_print(ValueType::try_from(instr_type1 as u8).unwrap()).0
                        )
                    }

                    Opcode::Conv => {
                        let from_type = ValueType::try_from(instr_type1 as u8).unwrap();
                        let to_type = ValueType::try_from(instr_type2 as u8).unwrap();
                        format!(
                            "{opcode:?}.{from_char}.{to_char} (pops: [{from_str}] -> pushes: [{to_str}])",
                            from_char = get_type_print(from_type).0,
                            to_char = get_type_print(to_type).0,
                            from_str = get_type_print(from_type).1,
                            to_str = get_type_print(to_type).1
                        )
                    }

                    Opcode::Push => {
                        let type_print =
                            get_type_print(ValueType::try_from(instr_type1 as u8).unwrap());
                        format!(
                            "{opcode:?}.{type1_char} 0x{extra_data:8X} (pops: [] -> pushes: [{type1_str}])",
                            type1_char = type_print.0,
                            type1_str = type_print.1,
                            extra_data = extra_data[0]
                        )
                    }

                    Opcode::PushI => {
                        format!(
                            "{opcode:?}.{type1_char} 0x{extra_data:8X} (pops: [] -> pushes: [{type1_str}])",
                            type1_char =
                                get_type_print(ValueType::try_from(instr_type1 as u8).unwrap()).0,
                            type1_str =
                                get_type_print(ValueType::try_from(instr_type1 as u8).unwrap()).1,
                            extra_data = extra_data[0]
                        )
                    }

                    Opcode::Pop => {
                        format!(
                            "{opcode:?}.{type1_char} (pops: [{type1_str}] -> pushes: [])",
                            type1_char =
                                get_type_print(ValueType::try_from(instr_type1 as u8).unwrap()).0,
                            type1_str =
                                get_type_print(ValueType::try_from(instr_type1 as u8).unwrap()).1
                        )
                    }

                    _ => format!("{opcode:?} (type1: 0x{instr_type1:X}, type2: 0x{instr_type2:X})"),
                }
            );
        }
    }
}
