use clap::Parser as ClapParser;

mod ast;
mod bytecode;
mod compiler;
mod disassembler;
mod encoder;
mod instruction;
mod lexer;
mod parser;
mod resolver;
mod vari;

use compiler::Compiler;
use lexer::Lexer;
use parser::Parser;
use resolver::Resolver;

use crate::disassembler::print_disassembly;

#[derive(ClapParser)]
#[command(name = "gmlc")]
#[command(about = "GameMaker Language compiler")]
struct Args {
    /// Input file
    input: String,

    /// Enable debug mode to print the generated bytecode
    #[arg(long)]
    debug: bool,

    /// Output file
    #[arg(short, long)]
    output: Option<String>,
}

fn main() {
    let args: Args = ClapParser::parse();

    let input = std::fs::read_to_string(&args.input).expect("Failed to read input file");

    let lexer = Lexer::new(input);
    let mut parser = Parser::new(lexer);

    let program = parser.parse_program();
    let mut compiler = Compiler::new();
    compiler.compile_program(&program);

    let mut resolver = Resolver::new();
    let resolved = resolver.resolve(compiler.instructions);

    let bytecode = encoder::encode(resolved);
    if args.debug {
        print_disassembly(&bytecode);
    }

    if args.output.is_none() {
        println!("No output file specified. Use -o <file> to specify an output file.");
    } else {
        let output_file = args.output.unwrap_or_else(|| "output.gmlc".to_string());
        std::fs::write(output_file, bytecode.data).expect("Failed to write output file");
    }
}
