use clap::Parser as ClapParser;

mod ast;
mod bytecode;
mod compiler;
mod encoder;
mod instruction;
mod lexer;
mod parser;
mod resolver;
mod vari;

use compiler::Compiler;
use lexer::Lexer;
use parser::Parser;
use resolver::Resolver;

use crate::bytecode::Opcode;

#[derive(ClapParser)]
#[command(name = "gmlc")]
#[command(about = "GameMaker Language compiler")]
struct Args {
    /// Input file
    input: String,

    /// Enable debug mode to print the generated bytecode
    #[arg(long)]
    debug: bool,

    /// Output file
    #[arg(short, long)]
    output: Option<String>,
}

fn main() {
    let args: Args = ClapParser::parse();

    let input = std::fs::read_to_string(&args.input).expect("Failed to read input file");

    let lexer = Lexer::new(input);
    let mut parser = Parser::new(lexer);

    let program = parser.parse_program();
    let mut compiler = Compiler::new();
    compiler.compile_program(&program);

    let mut resolver = Resolver::new();
    let resolved = resolver.resolve(compiler.instructions);

    let bytecode = encoder::encode(resolved);
    if args.debug {
        println!("Generated bytecode:");
        let mut current: Option<String> = None;

        for chunk in bytecode.data.chunks_exact(4) {
            let value = u32::from_le_bytes(chunk.try_into().unwrap());
            let opcode = (value >> 24) & 0xFF;

            if let Ok(op) = Opcode::try_from(opcode) {
                if let Some(line) = current.take() {
                    println!("{line})");
                }

                let type1 = (value >> 16) & 0xF;
                let type2 = (value >> 20) & 0xF;

                current = Some(format!(
                    "0x{value:08X}: {op:?} (type1: 0x{type1:X}, type2: 0x{type2:X}"
                ));
            } else if let Some(line) = current.as_mut() {
                line.push_str(&format!(", value: 0x{value:08X}"));
            }
        }

        if let Some(line) = current {
            println!("{line})");
        }
    }

    if args.output.is_none() {
        println!("No output file specified. Use -o <file> to specify an output file.");
    } else {
        let output_file = args.output.unwrap_or_else(|| "output.gmlc".to_string());
        std::fs::write(output_file, bytecode.data).expect("Failed to write output file");
    }
}
