#[derive(Clone, Copy, Debug)]
pub struct WadLayout {
    pub wad_version: u8,

    pub major: u32,
    pub minor: u32,
    pub release: u32,
    pub build: u32,

    pub compact_gen8: bool,
    pub has_display_name: bool,
    pub has_active_targets: bool,
    pub has_function_classifications: bool,
    pub has_debugger_port: bool,
    pub timestamp_is_64bit: bool,

    pub has_constants: bool,

    pub old_code_format: bool,

    pub gms2_room_tail: bool,
    pub gms2_3_sequences: bool,
}

impl WadLayout {
    pub fn for_version(wad_version: u8) -> Self {
        match wad_version {
            0..=8 => Self {
                wad_version,
                major: 1,
                minor: 0,
                release: 0,
                build: 198,
                compact_gen8: true,
                has_display_name: false,
                has_active_targets: false,
                has_function_classifications: false,
                has_debugger_port: false,
                timestamp_is_64bit: false,
                has_constants: false,
                old_code_format: true,
                gms2_room_tail: false,
                gms2_3_sequences: false,
            },
            9 => Self {
                wad_version,
                major: 1,
                minor: 0,
                release: 0,
                build: 300,
                compact_gen8: false,
                has_display_name: false,
                has_active_targets: false,
                has_function_classifications: false,
                has_debugger_port: false,
                timestamp_is_64bit: false,
                has_constants: true,
                old_code_format: true,
                gms2_room_tail: false,
                gms2_3_sequences: false,
            },
            10..=12 => Self {
                wad_version,
                major: 1,
                minor: 0,
                release: 0,
                build: 400,
                compact_gen8: false,
                has_display_name: true,
                has_active_targets: wad_version >= 11,
                has_function_classifications: wad_version >= 12,
                has_debugger_port: false,
                timestamp_is_64bit: false,
                has_constants: true,
                old_code_format: true,
                gms2_room_tail: false,
                gms2_3_sequences: false,
            },
            13 => Self {
                wad_version,
                major: 1,
                minor: 4,
                release: 0,
                build: 0,
                compact_gen8: false,
                has_display_name: true,
                has_active_targets: true,
                has_function_classifications: true,
                has_debugger_port: false,
                timestamp_is_64bit: true,
                has_constants: true,
                old_code_format: true,
                gms2_room_tail: false,
                gms2_3_sequences: false,
            },
            14 => Self {
                wad_version,
                major: 1,
                minor: 4,
                release: 9,
                build: 9999,
                compact_gen8: false,
                has_display_name: true,
                has_active_targets: true,
                has_function_classifications: true,
                has_debugger_port: true,
                timestamp_is_64bit: true,
                has_constants: true,
                old_code_format: true,
                gms2_room_tail: false,
                gms2_3_sequences: false,
            },
            15..=16 => Self {
                wad_version,
                major: 2,
                minor: 0,
                release: 0,
                build: 0,
                compact_gen8: false,
                has_display_name: true,
                has_active_targets: true,
                has_function_classifications: true,
                has_debugger_port: true,
                timestamp_is_64bit: true,
                has_constants: true,
                old_code_format: false,
                gms2_room_tail: true,
                gms2_3_sequences: false,
            },
            _ => Self {
                wad_version,
                major: 2,
                minor: 3,
                release: 0,
                build: 0,
                compact_gen8: false,
                has_display_name: true,
                has_active_targets: true,
                has_function_classifications: true,
                has_debugger_port: true,
                timestamp_is_64bit: true,
                has_constants: true,
                old_code_format: false,
                gms2_room_tail: true,
                gms2_3_sequences: true,
            },
        }
    }
}
